name: snake
description: A new Flutter projectt.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.3.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  get: ^4.1.4
  random_string: ^2.1.0
  rounded_loading_button: ^2.0.5
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/crunch.mp3
